### PR TITLE
NEXUS-10052: Bower does not work with context path

### PR DESCRIPTION
**Pull request by fjmilens3**
Possible fix for https://issues.sonatype.org/browse/NEXUS-10052

### CODE REVIEW

**Comment by kellyrob99** [comment]
+1 Seems reasonable provided that there are only ever the 2 path segments and they're both non-optional (I'm looking at you Docker /library edge-case!)

**Comment by peterlynch** [comment]
doesn't look like it will break your code but I have occasionally seen /context/path/ used in the wild via a reverse proxy.

**Comment by mrprescott** [comment]
+1

**Comment by fjmilens3** [comment]
Squash merged as a0594faea4973a8617087af41e0c10c22e2e3d0e.

**Pull request closed without merging**
