### PR TITLE
Create .travis.yml to resolve #1

### LINKED ISSUE #1: Any interest in adding CI support such as travis-ci?
It would be nice to see a few shields with build status for this package. I'd be willing to help set it up! Let me know..

### PR DESCRIPTION
**Pull request by evanjbowling**
Creating travis CI file for common node.js versions

### CODE REVIEW

**Comment by evanjbowling** [comment]
I believe I will need write access for this repository to set it up in travis CI. Let me know in the comments if that's ok, and I'll configure it.

**Comment by mosabua** [comment]
We can set up the hook and permissions to test this. Let me work with the other developers in the next days.

**Comment by mosabua** [comment]
Also from what I understand from https://docs.travis-ci.com/user/languages/javascript-with-nodejs this will run 

npm test

**Comment by DarthHater** [comment]
Hi there @evanjbowling before we work on this, do you mind filling out our CLA and sending it to me at jhesse at sonatype dot com

http://www.sonatype.org/SonatypeCLA.pdf

**Comment by fjmilens3** [comment]
@evanjbowling, nothing personal, but we tend to be very restrictive about handing out write access. We'll have to coordinate with our internal ops team and in the meantime @DarthHater will be contacting you regarding some legal paperwork that's required for all contributions. Hopefully you'll see some movement on this issue once we've been able to get things sorted out!

**Comment by evanjbowling** [comment]
This PR is very minimal and stale. Closing.

**Pull request closed without merging**
