### PR TITLE
update request version to fix security vulnerabilities

### PR DESCRIPTION
**Pull request by philtobias**
Updates major version of `request` to latest at this time to fix security vulnerabilities.

### CODE REVIEW

**Comment by cteyton** [comment]
:+1:

**Comment by fjmilens3** [comment]
We're taking a look at this as part of an overall update of our dependencies for the resolver. Thanks for bringing this to our attention!

(We'll close this issue once we merge in our PR, right now I plan to leave it open as a subtle reminder to ourselves.)

**Comment by fjmilens3** [comment]
Updated as part of https://github.com/sonatype/bower-nexus3-resolver/issues/15. Thanks for bringing this to our attention!

This should go out the next time we do a bower-nexus3-resolver release.

**Comment by DarthHater** [comment]
Fixed as a part of #15

**Comment by DarthHater** [comment]
@cteyton @philtobias we released this today as 1.0.2. Thanks again for the heads up and helping out. @philtobias do you have a link to the security vulnerability report, for this issues posterity sake?

**Pull request closed without merging**
